# Generated by Django 5.2.5 on 2025-09-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='delivery_price',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=8),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
